CREATE TABLE SchemaHistory
(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,

    Version INTEGER NOT NULL UNIQUE,
	DateApplied INTEGER NOT NULL,
	ScriptApplied TEXT NOT NULL
);

CREATE TABLE Blogs
(
    Id INTEGER NOT NULL CONSTRAINT PK_Blogs PRIMARY KEY AUTOINCREMENT,

    Url TEXT NOT NULL
);
CREATE INDEX Blogs_ValueIndex ON Blogs (Url);